markdown: kramdown
kramdown:
  hard_wrap: false
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-optional-front-matter
  - "jekyll-github-metadata"
relative_links:
  enabled: true
  collections: true
title: Privacy, Security and Anonymity
description: A project from the Anonymous Planet organization.
theme: jekyll-theme-cayman
author: AnonymousPlanet
github:
  home_url: index.html
  license_url: LICENSE.html
  repository_url: https://github.com/Anon-Planet
  guide_url: https://anonymousplanet-ng.org
  repository_name: Anonymous Planet
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      sitemap: true
locale: "en-US"
author:
  name: AnonymousPlanet
social:
  name: AnonymousPlanet
  links:
    - https://twitter.com/AnonyPla
    - https://github.com/Anon-Planet
    - https://matrix.to/#/#privacy-security-anonymity:matrix.org
    - https://mastodon.social/@anonymousplanet
optional_front_matter:
  remove_originals: true
